-- CCV corpus, slim PostgreSQL schema (rhyme-focused).
-- Generated by tools/ccv-to-sql/build.py.

BEGIN;

CREATE TABLE authors (
    id        SERIAL PRIMARY KEY,
    identity  TEXT NOT NULL UNIQUE,
    name      TEXT NOT NULL,
    born      INTEGER,
    died      INTEGER
);

CREATE TABLE books (
    id          TEXT PRIMARY KEY,                              -- corpus book_id, e.g. "0001"
    author_id   INTEGER REFERENCES authors(id),
    b_title     TEXT,
    b_subtitle  TEXT,
    publisher   TEXT,
    place       TEXT,
    year        TEXT,                                          -- kept TEXT: corpus has "[1923]" etc.
    edition     TEXT,
    pages       TEXT,
    signature   TEXT,
    motto       TEXT,
    motto_aut   TEXT
);

CREATE TABLE poems (
    id              BIGSERIAL PRIMARY KEY,
    book_id         TEXT NOT NULL REFERENCES books(id),
    corpus_poem_id  TEXT NOT NULL,                             -- per-book poem_id from JSON (not globally unique)
    author_id       INTEGER REFERENCES authors(id),
    p_title         TEXT,
    dedication      TEXT,
    UNIQUE (book_id, corpus_poem_id)
);

CREATE TABLE stanzas (
    id            BIGSERIAL PRIMARY KEY,
    poem_id       BIGINT NOT NULL REFERENCES poems(id),
    stanza_index  INTEGER NOT NULL,
    UNIQUE (poem_id, stanza_index)
);

CREATE TABLE verses (
    id           BIGSERIAL PRIMARY KEY,
    stanza_id    BIGINT NOT NULL REFERENCES stanzas(id),
    verse_index  INTEGER NOT NULL,
    text         TEXT NOT NULL,
    rhyme_group  INTEGER,                                      -- per-stanza rhyme group id
    last_token   TEXT,                                         -- lowercased surface form of last word
    last_lemma   TEXT,                                         -- lemma of last word
    last_phoebe  TEXT,                                         -- phonetic transcription of last word
    UNIQUE (stanza_id, verse_index)
);

-- Standalone rhyme lookup (no FK to verses; pre-aggregated from CCV rhyme_group).
CREATE TABLE tokens (
    id        SERIAL PRIMARY KEY,
    word      TEXT NOT NULL UNIQUE,                            -- lowercased surface form
    lemma     TEXT,                                            -- dominant lemma for this surface form
    phoebe    TEXT,                                            -- dominant phonetic transcription
    n_verses  INTEGER NOT NULL                                 -- # verses where this is the last token
);

CREATE TABLE rhymes (
    token_a_id  INTEGER NOT NULL REFERENCES tokens(id),
    token_b_id  INTEGER NOT NULL REFERENCES tokens(id),
    score       INTEGER NOT NULL,                              -- # CCV stanzas where the pair shares rhyme_group
    PRIMARY KEY (token_a_id, token_b_id),
    CHECK (token_a_id < token_b_id)
);

COMMIT;
