#!/usr/bin/env python3
"""Convert CCV JSON corpus (ccv/*.json) to a slim PostgreSQL dump.

Tuned for LLM-driven rhyme lookup. Compared to the previous full export this
drops the per-word morph/phonetic tables and denormalizes the *last word* of
each verse onto `verses` (token_lc / lemma / phoebe), bringing the dump from
~1.4 GB down to ~230 MB.

Dropped vs. full export:
    - words        (per-word morph / xsampa / phoebe / lemma)
    - metres       (per-verse foot / clause / pattern)
    - punctuation  (already present in verses.text)
    - verses.stress

Outputs into the directory passed via --out (default: out/), split into
schema/ (DDL + post-load fixups) and data/ (INSERT dumps):

    schema/schema.sql      tables, PKs, FKs
    schema/indexes.sql     secondary indexes (run after data load)
    schema/sequences.sql   setval() for SERIAL/BIGSERIAL columns
    data/data_authors.sql  one INSERT-batched dump per table
    data/data_books.sql
    data/data_poems.sql
    data/data_stanzas.sql
    data/data_verses.sql

Suggested load order is printed at the end of the run.
"""
from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from pathlib import Path


# --- SQL emit helpers ---------------------------------------------------------

def sql_str(s) -> str:
    # Assumes standard_conforming_strings=on (PG default since 9.1), so only
    # single quotes need to be doubled; backslashes are literal.
    if s is None:
        return "NULL"
    if not isinstance(s, str):
        s = str(s)
    return "'" + s.replace("'", "''") + "'"


def sql_int(v) -> str:
    if v is None or v == "":
        return "NULL"
    try:
        return str(int(v))
    except (TypeError, ValueError):
        return "NULL"


# --- Static SQL ---------------------------------------------------------------

SCHEMA_SQL = """\
-- CCV corpus, slim PostgreSQL schema (rhyme-focused).
-- Generated by tools/ccv-to-sql/build.py.

BEGIN;

CREATE TABLE authors (
    id        SERIAL PRIMARY KEY,
    identity  TEXT NOT NULL UNIQUE,
    name      TEXT NOT NULL,
    born      INTEGER,
    died      INTEGER
);

CREATE TABLE books (
    id          TEXT PRIMARY KEY,                              -- corpus book_id, e.g. "0001"
    author_id   INTEGER REFERENCES authors(id),
    b_title     TEXT,
    b_subtitle  TEXT,
    publisher   TEXT,
    place       TEXT,
    year        TEXT,                                          -- kept TEXT: corpus has "[1923]" etc.
    edition     TEXT,
    pages       TEXT,
    signature   TEXT,
    motto       TEXT,
    motto_aut   TEXT
);

CREATE TABLE poems (
    id              BIGSERIAL PRIMARY KEY,
    book_id         TEXT NOT NULL REFERENCES books(id),
    corpus_poem_id  TEXT NOT NULL,                             -- per-book poem_id from JSON (not globally unique)
    author_id       INTEGER REFERENCES authors(id),
    p_title         TEXT,
    dedication      TEXT,
    UNIQUE (book_id, corpus_poem_id)
);

CREATE TABLE stanzas (
    id            BIGSERIAL PRIMARY KEY,
    poem_id       BIGINT NOT NULL REFERENCES poems(id),
    stanza_index  INTEGER NOT NULL,
    UNIQUE (poem_id, stanza_index)
);

CREATE TABLE verses (
    id           BIGSERIAL PRIMARY KEY,
    stanza_id    BIGINT NOT NULL REFERENCES stanzas(id),
    verse_index  INTEGER NOT NULL,
    text         TEXT NOT NULL,
    rhyme_group  INTEGER,                                      -- per-stanza rhyme group id
    last_token   TEXT,                                         -- lowercased surface form of last word
    last_lemma   TEXT,                                         -- lemma of last word
    last_phoebe  TEXT,                                         -- phonetic transcription of last word
    UNIQUE (stanza_id, verse_index)
);

-- Standalone rhyme lookup (no FK to verses; pre-aggregated from CCV rhyme_group).
CREATE TABLE tokens (
    id        SERIAL PRIMARY KEY,
    word      TEXT NOT NULL UNIQUE,                            -- lowercased surface form
    lemma     TEXT,                                            -- dominant lemma for this surface form
    phoebe    TEXT,                                            -- dominant phonetic transcription
    n_verses  INTEGER NOT NULL                                 -- # verses where this is the last token
);

CREATE TABLE rhymes (
    token_a_id  INTEGER NOT NULL REFERENCES tokens(id),
    token_b_id  INTEGER NOT NULL REFERENCES tokens(id),
    score       INTEGER NOT NULL,                              -- # CCV stanzas where the pair shares rhyme_group
    PRIMARY KEY (token_a_id, token_b_id),
    CHECK (token_a_id < token_b_id)
);

COMMIT;
"""

INDEXES_SQL = """\
-- Secondary indexes. Run after data load for fastest import.

CREATE INDEX idx_books_author       ON books(author_id);
CREATE INDEX idx_poems_book         ON poems(book_id);
CREATE INDEX idx_poems_author       ON poems(author_id);
CREATE INDEX idx_stanzas_poem       ON stanzas(poem_id);
CREATE INDEX idx_verses_stanza      ON verses(stanza_id);
CREATE INDEX idx_verses_rhyme       ON verses(rhyme_group);
CREATE INDEX idx_verses_last_token  ON verses(last_token);
CREATE INDEX idx_verses_last_lemma  ON verses(last_lemma);

CREATE INDEX idx_tokens_lemma       ON tokens(lemma);
CREATE INDEX idx_rhymes_a_score     ON rhymes(token_a_id, score DESC);
CREATE INDEX idx_rhymes_b_score     ON rhymes(token_b_id, score DESC);
"""


def is_valid_word(w: str | None) -> bool:
    """Accept tokens of length >= 2 with at least one alphabetic char."""
    if not w or len(w) < 2:
        return False
    return any(c.isalpha() for c in w)


# --- Buffered writer ----------------------------------------------------------

class BatchWriter:
    """Buffer rows into multi-row INSERTs and flush when batch_size is reached."""

    def __init__(self, path: Path, table: str, columns: list[str], batch_size: int):
        self.fh = path.open("w", encoding="utf-8")
        self.fh.write(f"-- {table}\nBEGIN;\n")
        self.prefix = f"INSERT INTO {table} (" + ", ".join(columns) + ") VALUES\n"
        self.batch_size = batch_size
        self.buf: list[str] = []
        self.rows = 0

    def write(self, values: list[str]) -> None:
        self.buf.append("(" + ", ".join(values) + ")")
        self.rows += 1
        if len(self.buf) >= self.batch_size:
            self.flush()

    def flush(self) -> None:
        if not self.buf:
            return
        self.fh.write(self.prefix)
        self.fh.write(",\n".join(self.buf))
        self.fh.write(";\n")
        self.buf.clear()

    def close(self) -> None:
        self.flush()
        self.fh.write("COMMIT;\n")
        self.fh.close()


# --- Main ---------------------------------------------------------------------

def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--corpus", type=Path, default=Path("ccv"),
                    help="directory with CCV JSON files (default: ccv)")
    ap.add_argument("--out", type=Path, default=Path("out"),
                    help="output directory for SQL files (default: out)")
    ap.add_argument("--batch-size", type=int, default=500,
                    help="rows per multi-row INSERT (default: 500)")
    ap.add_argument("--limit", type=int, default=0,
                    help="process only first N JSON files (0 = all)")
    args = ap.parse_args()

    schema_dir = args.out / "schema"
    data_dir = args.out / "data"
    schema_dir.mkdir(parents=True, exist_ok=True)
    data_dir.mkdir(parents=True, exist_ok=True)

    (schema_dir / "schema.sql").write_text(SCHEMA_SQL, encoding="utf-8")
    (schema_dir / "indexes.sql").write_text(INDEXES_SQL, encoding="utf-8")

    files = sorted(args.corpus.glob("*.json"))
    if not files:
        print(f"No JSON files found in {args.corpus}", file=sys.stderr)
        return 1
    if args.limit > 0:
        files = files[: args.limit]

    bs = args.batch_size
    authors_w = BatchWriter(data_dir / "data_authors.sql", "authors",
                            ["id", "identity", "name", "born", "died"], bs)
    books_w = BatchWriter(data_dir / "data_books.sql", "books",
                          ["id", "author_id", "b_title", "b_subtitle", "publisher", "place",
                           "year", "edition", "pages", "signature", "motto", "motto_aut"], bs)
    poems_w = BatchWriter(data_dir / "data_poems.sql", "poems",
                          ["id", "book_id", "corpus_poem_id", "author_id", "p_title", "dedication"], bs)
    stanzas_w = BatchWriter(data_dir / "data_stanzas.sql", "stanzas",
                            ["id", "poem_id", "stanza_index"], bs)
    verses_w = BatchWriter(data_dir / "data_verses.sql", "verses",
                           ["id", "stanza_id", "verse_index", "text", "rhyme_group",
                            "last_token", "last_lemma", "last_phoebe"], bs)

    authors_seen: dict[str, int] = {}
    seen_books: set[str] = set()
    next_author_id = 1
    next_poem_id = 1
    next_stanza_id = 1
    next_verse_id = 1

    # In-memory aggregators for the standalone tokens/rhymes tables.
    # All valid last_tokens land in tokens; historical pairs land in rhymes.
    token_n_verses: Counter[str] = Counter()
    token_lemmas: dict[str, Counter[str]] = {}
    token_phoebes: dict[str, Counter[str]] = {}
    historical_pairs: Counter[tuple[str, str]] = Counter()

    def get_author_id(author: dict | None) -> str:
        nonlocal next_author_id
        if not author or not author.get("identity"):
            return "NULL"
        ident = author["identity"]
        aid = authors_seen.get(ident)
        if aid is None:
            aid = next_author_id
            next_author_id += 1
            authors_seen[ident] = aid
            authors_w.write([
                str(aid),
                sql_str(ident),
                sql_str(author.get("name") or ident),
                sql_int(author.get("born")),
                sql_int(author.get("died")),
            ])
        return str(aid)

    for i, fp in enumerate(files, 1):
        with fp.open(encoding="utf-8") as fh:
            poems = json.load(fh)
        for poem in poems:
            book_id = poem["book_id"]
            corpus_poem_id = poem["poem_id"]

            b_auth = get_author_id(poem.get("b_author"))
            p_auth = get_author_id(poem.get("p_author"))
            biblio = poem.get("biblio") or {}

            if book_id not in seen_books:
                seen_books.add(book_id)
                books_w.write([
                    sql_str(book_id), b_auth,
                    sql_str(biblio.get("b_title")),
                    sql_str(biblio.get("b_subtitle")),
                    sql_str(biblio.get("publisher")),
                    sql_str(biblio.get("place")),
                    sql_str(biblio.get("year")),
                    sql_str(biblio.get("edition")),
                    sql_str(biblio.get("pages")),
                    sql_str(biblio.get("signature")),
                    sql_str(biblio.get("motto")),
                    sql_str(biblio.get("motto_aut")),
                ])

            poem_id = next_poem_id
            next_poem_id += 1
            poems_w.write([
                str(poem_id), sql_str(book_id), sql_str(corpus_poem_id), p_auth,
                sql_str(biblio.get("p_title")),
                sql_str(biblio.get("dedication")),
            ])

            for st_idx, stanza in enumerate(poem.get("body") or []):
                stanza_id = next_stanza_id
                next_stanza_id += 1
                stanzas_w.write([str(stanza_id), str(poem_id), str(st_idx)])

                # Group last_tokens by rhyme_group within this stanza for pair emission.
                stanza_groups: dict[int, list[str]] = {}

                for v_idx, verse in enumerate(stanza):
                    verse_id = next_verse_id
                    next_verse_id += 1
                    rhyme = verse.get("rhyme")
                    words = verse.get("words") or []
                    last = words[-1] if words else None
                    last_token = last.get("token_lc") if last else None
                    last_lemma = last.get("lemma") if last else None
                    last_phoebe = last.get("phoebe") if last else None
                    verses_w.write([
                        str(verse_id), str(stanza_id), str(v_idx),
                        sql_str(verse.get("text")),
                        sql_int(rhyme) if rhyme is not None else "NULL",
                        sql_str(last_token) if last else "NULL",
                        sql_str(last_lemma) if last else "NULL",
                        sql_str(last_phoebe) if last else "NULL",
                    ])

                    if not is_valid_word(last_token):
                        continue
                    token_n_verses[last_token] += 1
                    if last_lemma:
                        token_lemmas.setdefault(last_token, Counter())[last_lemma] += 1
                    if last_phoebe:
                        token_phoebes.setdefault(last_token, Counter())[last_phoebe] += 1
                    if rhyme is not None:
                        try:
                            rg = int(rhyme)
                        except (TypeError, ValueError):
                            rg = None
                        if rg is not None:
                            stanza_groups.setdefault(rg, []).append(last_token)

                # Emit all unordered pairs of last_tokens within the same rhyme_group.
                for tokens_in_group in stanza_groups.values():
                    n = len(tokens_in_group)
                    if n < 2:
                        continue
                    for i in range(n):
                        a = tokens_in_group[i]
                        for j in range(i + 1, n):
                            b = tokens_in_group[j]
                            if a == b:
                                continue
                            pair = (a, b) if a < b else (b, a)
                            historical_pairs[pair] += 1

        if i % 50 == 0 or i == len(files):
            print(f"  processed {i}/{len(files)} files "
                  f"(poems={next_poem_id - 1}, verses={next_verse_id - 1})",
                  file=sys.stderr)

    for w in (authors_w, books_w, poems_w, stanzas_w, verses_w):
        w.close()

    # --- Emit standalone tokens/rhymes tables ---
    # Sort tokens alphabetically for stable id assignment; this also makes
    # (word_a < word_b) imply (a_id < b_id), so the rhymes CHECK holds for free.
    sorted_tokens = sorted(token_n_verses.keys())
    token_to_id = {w: i + 1 for i, w in enumerate(sorted_tokens)}

    tokens_w = BatchWriter(data_dir / "data_tokens.sql", "tokens",
                           ["id", "word", "lemma", "phoebe", "n_verses"], bs)
    token_dominant_lemma: dict[str, str] = {}
    for word in sorted_tokens:
        lemma_counter = token_lemmas.get(word)
        lemma = lemma_counter.most_common(1)[0][0] if lemma_counter else None
        phoebe_counter = token_phoebes.get(word)
        phoebe = phoebe_counter.most_common(1)[0][0] if phoebe_counter else None
        if lemma:
            token_dominant_lemma[word] = lemma
        tokens_w.write([
            str(token_to_id[word]),
            sql_str(word),
            sql_str(lemma),
            sql_str(phoebe),
            str(token_n_verses[word]),
        ])
    tokens_w.close()

    rhymes_w = BatchWriter(data_dir / "data_rhymes.sql", "rhymes",
                           ["token_a_id", "token_b_id", "score"], bs)
    rhymes_emitted = 0
    rhymes_skipped_lemma = 0
    for (word_a, word_b), score in historical_pairs.items():
        a_id = token_to_id.get(word_a)
        b_id = token_to_id.get(word_b)
        if a_id is None or b_id is None:
            # Either token was filtered out by is_valid_word.
            continue
        lemma_a = token_dominant_lemma.get(word_a)
        lemma_b = token_dominant_lemma.get(word_b)
        if lemma_a and lemma_b and lemma_a.lower() == lemma_b.lower():
            rhymes_skipped_lemma += 1
            continue
        # word_a < word_b (sorted tuple) implies a_id < b_id given alphabetical id assignment.
        if a_id < b_id:
            rhymes_w.write([str(a_id), str(b_id), str(score)])
        else:
            rhymes_w.write([str(b_id), str(a_id), str(score)])
        rhymes_emitted += 1
    rhymes_w.close()

    print(f"  tokens: {len(sorted_tokens)}, "
          f"rhymes: {rhymes_emitted} (skipped {rhymes_skipped_lemma} same-lemma pairs)",
          file=sys.stderr)

    # SERIAL/BIGSERIAL sequences are not advanced by manual INSERTs of id values;
    # bump them so future inserts don't collide.
    (schema_dir / "sequences.sql").write_text("\n".join([
        "-- Reset sequences to max(id) after the bulk load.",
        f"SELECT setval('authors_id_seq', {max(next_author_id - 1, 1)});",
        f"SELECT setval('poems_id_seq',   {max(next_poem_id - 1, 1)});",
        f"SELECT setval('stanzas_id_seq', {max(next_stanza_id - 1, 1)});",
        f"SELECT setval('verses_id_seq',  {max(next_verse_id - 1, 1)});",
        f"SELECT setval('tokens_id_seq',  {max(len(sorted_tokens), 1)});",
        "",
    ]), encoding="utf-8")

    print(f"\nDone. Outputs in {args.out}/", file=sys.stderr)
    print("Suggested psql load order:", file=sys.stderr)
    for path in (schema_dir / "schema.sql",
                 data_dir / "data_authors.sql",
                 data_dir / "data_books.sql",
                 data_dir / "data_poems.sql",
                 data_dir / "data_stanzas.sql",
                 data_dir / "data_verses.sql",
                 data_dir / "data_tokens.sql",
                 data_dir / "data_rhymes.sql",
                 schema_dir / "indexes.sql",
                 schema_dir / "sequences.sql"):
        print(f"  psql -f {path}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
